INSERT INTO alumno VALUES(NULL, 'Jorge', 'Hernandez', 'Garcia', 'jherd@uv.mx', '2004-05-18', NULL);
INSERT INTO alumno VALUES(NULL, 'Samuel', 'Martinez', 'Herrera', 'smart@uv.mx', '2003-26-10', NULL);
INSERT INTO alumno VALUES(NULL, 'Fatima', 'Castillo', 'Jimenez', 'fcast@uv.mx', '2004-03-08', NULL);
INSERT INTO alumno VALUES(NULL, 'Valeria', 'Gonzales', 'Trujillo', 'vgonz@uv.mx', '1999-06-01', NULL);
INSERT INTO alumno VALUES(NULL, 'Jose Manuel', 'Iñiguez', 'Lopez', 'jinig@uv.mx', '1998-03-31', NULL);
INSERT INTO alumno VALUES(NULL, 'Amir Isaid', 'Ochoa', 'Tadeo', 'aocho@uv.mx', '2001-09-10', NULL);
INSERT INTO alumno VALUES(NULL, 'Sebastián', 'Rivera', 'Fernandez', 'srive@uv.mx', '2004-04-23', NULL);
INSERT INTO alumno VALUES(NULL, 'Karen Esperanza', 'Lopez', 'Yoval', 'klope@uv.mx', '2004-10-26', NULL);
INSERT INTO alumno VALUES(NULL, 'Joseline', 'Vazquez', 'Fernandez', 'jvazq@uv.mx', '2004-09-21', NULL);
INSERT INTO alumno VALUES(NULL, 'Víctor Manuel', 'Monge', 'Morales', 'vmong@uv.mx', '2000-02-12', NULL);

INSERT INTO carrera VALUES(NULL, 'LIS', 'Licenciatura en Ingeníeria de Software');
INSERT INTO carrera VALUES(NULL, 'LICIC', 'Licenciatura en Ingeniería en Ciberseguridad e Infraestructura de Computo');
INSERT INTO carrera VALUES(NULL, 'LISTI', 'Licenciatura en Ingeníeria en Sistemas y Tecnologías de la Información');
INSERT INTO carrera VALUES(NULL, 'LE', 'Licenciatura en Estadística');
INSERT INTO carrera VALUES(NULL, 'LRSC', 'Licenciatura en Redes y Servicios de Computo');
INSERT INTO carrera VALUES(NULL, 'LTC', 'Licenciatura en Tecnologías Computacionales');

INSERT INTO areaFormacion VALUES(NULL, 'Básica disciplinar');
INSERT INTO areaFormacion VALUES(NULL, 'Iniciación a la disciplina');
INSERT INTO areaFormacion VALUES(NULL, 'Disciplinaria');
INSERT INTO areaFormacion VALUES(NULL, 'Terminal');
INSERT INTO areaFormacion VALUES(NULL, 'Elección Libre');

INSERT INTO materia VALUES(NULL, 1, 2, 'Medición de Software', 7, 6, 'Seguimiento y control del desarrollo de software');
INSERT INTO materia VALUES(NULL, 1, 2, 'Diseño de Software', 5, 9, 'Estrategias, métodos, técnicas y herramientas para el diseño de software');
INSERT INTO materia VALUES(NULL, 1, 2, 'Requisitos de Software', 3, 8, 'Identifica funcionalidades que debe cubrir el software a desarrollar');
INSERT INTO materia VALUES(NULL, 1, 1, 'Habilidades de Comunicación', 2, 6, 'Transmisión de ideas de manera clara y concisa');
INSERT INTO materia VALUES(NULL, 1, 5, 'Aplicaciones web para el aprendizaje', 4, 3, 'Conocer las diferentes apps para el aprendizaje');
INSERT INTO materia VALUES(NULL, 2, 4, 'Servicios Multimedia', 7, 6, 'Transmisión de elementos multimedia en Internet');
INSERT INTO materia VALUES(NULL, 2, 3, 'Programación Segura', 7, 7, 'Identifica los principales riesgos y amenazas en la construcción de software');
INSERT INTO materia VALUES(NULL, 2, 3, 'Enrutamiento básico', 3, 8, 'Enrutamiento estático y dinámico con protocolos vector distancia');
INSERT INTO materia VALUES(NULL, 2, 4, 'Introducción a la Ciberseguridad', 1, 7, 'Estrategias de ciberseguridad orientadas a la protección de información');
INSERT INTO materia VALUES(NULL, 2, 5, 'Ciudadanía Digital', 4, 6, 'Conceptos sobre los usuarios digitales');
INSERT INTO materia VALUES(NULL, 3, 3, 'Networking', 3, 9, 'Realiza la correcta y funcional conectividad entre dispositivos de red');
INSERT INTO materia VALUES(NULL, 3, 3, 'Experiencia de Usuario', 4, 8, 'Construir sistemas de software a partir de un análisis centrado en el usuario');
INSERT INTO materia VALUES(NULL, 3, 4, 'Videojuegos Serios', 8, 6, 'Producción de recursos educativos particularmente juegos');
INSERT INTO materia VALUES(NULL, 3, 1, 'Literacidad Digital', 1, 6, 'Emplea herramientas digitales que permitan búsquedas y producción efectiva de información');
INSERT INTO materia VALUES(NULL, 3, 5, 'Excel y aplicaciones', 6, 5, 'Uso de Excel y sus aplicaciones en el ambito escolar');
INSERT INTO materia VALUES(NULL, 4, 3, 'Probabilidad I', 3, 8, 'Utiliza los principios, conceptos y reglas de la probabilidad');
INSERT INTO materia VALUES(NULL, 4, 1, 'Calculo aplicado a la Estadística I', 1, 9, 'Teoría cálculo diferencial e integral de una variable');
INSERT INTO materia VALUES(NULL, 4, 4, 'Bioestadística', 7, 6, 'Conocimientos especializados en áreas determinadas como las ciencias biológicas');
INSERT INTO materia VALUES(NULL, 4, 3, 'Muestreo', 3, 8, 'Diseño e implementacion de esquemas de muestreo');
INSERT INTO materia VALUES(NULL, 4, 5, 'Competencias para la empleabilidad', 6, 6, 'Presentacion de las competencias para la empleabilidad');
INSERT INTO materia VALUES(NULL, 5, 4, 'Práctica de redes', 7, 6, 'Identifica vulnerabilidades en sistemas de cómputo');
INSERT INTO materia VALUES(NULL, 5, 3, 'Redes', 3, 6, 'Conceptos básicos relacionados con los diferentes modelos, topologías y tipos de redes');
INSERT INTO materia VALUES(NULL, 5, 3, 'Arquitectura en Red', 4, 7, 'Construye LAN y WLAN bajo los estándares y normas de diseño');
INSERT INTO materia VALUES(NULL, 5, 3, 'Administración de Servidores', 5, 8, 'Administracion de un servidor con servicios basicos de computo');
INSERT INTO materia VALUES(NULL, 5, 5, 'Biblioteca Virtual', 5, 6, 'Alfabetizacion en la búsqueda y recuperación de información en línea');
INSERT INTO materia VALUES(NULL, 6, 3, 'Bases de Datos', 3, 9, 'Construye adecuadamente bases de datos relacionales');
INSERT INTO materia VALUES(NULL, 6, 4, 'Graficación', 7, 6, 'Constituir y generar gráficos por computadora');
INSERT INTO materia VALUES(NULL, 6, 3, 'Desarrollo Móvil', 6, 8, 'Técnicas para el desarrollo de aplicaciones móviles');
INSERT INTO materia VALUES(NULL, 6, 1, 'Introducción a la Programación', 1, 8, 'Diseña algoritmos computacionales');
INSERT INTO materia VALUES(NULL, 6, 5, 'Robótica Lúdica', 5, 6, 'Diseño de mecanismos electrómecánicos programables');

INSERT INTO gradoEstudio VALUES(NULL, 'Licenciatura');
INSERT INTO gradoEstudio VALUES(NULL, 'Maestría');
INSERT INTO gradoEstudio VALUES(NULL, 'Doctorado');

INSERT INTO profesor VALUES(NULL, 1, 'Claudia', 'Morales', 'Carmona', 'cmorc@uv.mx');
INSERT INTO profesor VALUES(NULL, 2, 'Rubí', 'Perez', 'Gutierrez', 'rperg@uv.mx');
INSERT INTO profesor VALUES(NULL, 2, 'William', 'León', 'Torres', 'wleot@uv.mx');
INSERT INTO profesor VALUES(NULL, 1, 'Scarlet', 'Dominguez', 'García', 'sdomg@uv.mx');
INSERT INTO profesor VALUES(NULL, 2, 'Gabriela', 'Orozco', 'Martinez', 'gorom@uv.mx');
INSERT INTO profesor VALUES(NULL, 2, 'Guillermo Humberto', 'Vera', 'Amaro', 'gvera@uv.mx');
INSERT INTO profesor VALUES(NULL, 2, 'José Guillermo', 'Hernandez', 'Calderón', 'jherc@uv.mx');
INSERT INTO profesor VALUES(NULL, 3, 'Isabel', 'Fernandez', 'Zuñiga', 'iferz@uv.mx');
INSERT INTO profesor VALUES(NULL, 3, 'María del Pilar', 'Elizondo', 'Dominguez', 'melid@uv.mx');
INSERT INTO profesor VALUES(NULL, 2, 'Cristian', 'Ramirez', 'Quinto', 'cramq@uv.mx');
INSERT INTO profesor VALUES(NULL, 3, 'Vicente Ramón', 'Contreras', 'Velazquez', 'vconv@uv.mx');
INSERT INTO profesor VALUES(NULL, 2, 'Agustín', 'Gonzalez', 'Torres', 'agont@uv.mx');
INSERT INTO profesor VALUES(NULL, 1, 'Román', 'Solis', 'Palacios', 'rsolp@uv.mx');
INSERT INTO profesor VALUES(NULL, 1, 'Juana Elisa', 'Escalante', 'Vega', 'jescv@uv.mx');
INSERT INTO profesor VALUES(NULL, 1, 'José Luis', 'Munzon', 'Herrera', 'jmunh@uv.mx');

INSERT INTO periodoEscolar VALUES(NULL, 'Febrero-Agosto 2020', '2020-02-02', '2020-08-16');
INSERT INTO periodoEscolar VALUES(NULL, 'Agosto-Enero 2020-21', '2020-08-17', '2021-01-08');
INSERT INTO periodoEscolar VALUES(NULL, 'Agosto-Enero 2021-22', '2021-08-04', '2022-01-06');
INSERT INTO periodoEscolar VALUES(NULL, 'Febrero-Agosto 2022', '2022-02-17', '2022-08-06');
INSERT INTO periodoEscolar VALUES(NULL, 'Agosto-Diciembre 2022', '2022-08-01', '2022-12-20');

INSERT INTO oferta VALUES(NULL, 1, 1, 2);
INSERT INTO oferta VALUES(NULL, 1, 2, 3);
INSERT INTO oferta VALUES(NULL, 2, 3, 1);
INSERT INTO oferta VALUES(NULL, 3, 4, 5);
INSERT INTO oferta VALUES(NULL, 5, 5, 11);
INSERT INTO oferta VALUES(NULL, 4, 6, 8);
INSERT INTO oferta VALUES(NULL, 3, 7, 4);
INSERT INTO oferta VALUES(NULL, 5, 8, 10);
INSERT INTO oferta VALUES(NULL, 2, 9, 12);
INSERT INTO oferta VALUES(NULL, 1, 10, 5);
INSERT INTO oferta VALUES(NULL, 4, 11, 6);
INSERT INTO oferta VALUES(NULL, 2, 12, 9);
INSERT INTO oferta VALUES(NULL, 3, 13, 7);
INSERT INTO oferta VALUES(NULL, 2, 14, 3);
INSERT INTO oferta VALUES(NULL, 1, 15, 14);
INSERT INTO oferta VALUES(NULL, 4, 16, 15);
INSERT INTO oferta VALUES(NULL, 5, 17, 1);
INSERT INTO oferta VALUES(NULL, 2, 18, 4);
INSERT INTO oferta VALUES(NULL, 1, 19, 8);
INSERT INTO oferta VALUES(NULL, 4, 20, 3);
INSERT INTO oferta VALUES(NULL, 2, 21, 6);
INSERT INTO oferta VALUES(NULL, 1, 22, 12);
INSERT INTO oferta VALUES(NULL, 2, 23, 11);
INSERT INTO oferta VALUES(NULL, 5, 24, 7);
INSERT INTO oferta VALUES(NULL, 3, 25, 15);
INSERT INTO oferta VALUES(NULL, 1, 26, 9);
INSERT INTO oferta VALUES(NULL, 4, 27, 2);
INSERT INTO oferta VALUES(NULL, 5, 28, 13);
INSERT INTO oferta VALUES(NULL, 2, 29, 10);
INSERT INTO oferta VALUES(NULL, 1, 30, 13);

INSERT INTO cursa VALUES(1, 1, 9.3);
INSERT INTO cursa VALUES(1, 2, 6.7);
INSERT INTO cursa VALUES(1, 3, 8.3);
INSERT INTO cursa VALUES(1, 4, 5.3);
INSERT INTO cursa VALUES(9, 2, 10);
INSERT INTO cursa VALUES(9, 3, 8.5);
INSERT INTO cursa VALUES(9, 2, 7.7);
INSERT INTO cursa VALUES(3, 5, 5.4);
INSERT INTO cursa VALUES(3, 6, 9.8);
INSERT INTO cursa VALUES(3, 8, 10);
INSERT INTO cursa VALUES(3, 9, 7.5);
INSERT INTO cursa VALUES(7, 7, 8.2);
INSERT INTO cursa VALUES(7, 6, 9.4);
INSERT INTO cursa VALUES(7, 8, 7.1);
INSERT INTO cursa VALUES(2, 10, 5.8);
INSERT INTO cursa VALUES(2, 14, 6);
INSERT INTO cursa VALUES(2, 12, 8.3);
INSERT INTO cursa VALUES(6, 11, 9);
INSERT INTO cursa VALUES(6, 13, 8.9);
INSERT INTO cursa VALUES(6, 10, 7);
INSERT INTO cursa VALUES(4, 15, 5.2);
INSERT INTO cursa VALUES(4, 18, 4.5);
INSERT INTO cursa VALUES(4, 17, 7.7);
INSERT INTO cursa VALUES(5, 20, 10);
INSERT INTO cursa VALUES(5, 21, 7.9);
INSERT INTO cursa VALUES(5, 22, 7);
INSERT INTO cursa VALUES(5, 23, 9.1);
INSERT INTO cursa VALUES(5, 24, 5);
INSERT INTO cursa VALUES(8, 26, 8.7);
INSERT INTO cursa VALUES(8, 27, 5.7);
INSERT INTO cursa VALUES(8, 29, 10);
INSERT INTO cursa VALUES(10, 28, 9);
INSERT INTO cursa VALUES(10, 31, 6.2);
INSERT INTO cursa VALUES(10, 25, 7);


//SELECT TIMESTAMPDIFF(YEAR, fecha_nacimiento, CURDATE()) AS edad FROM alumno;